import { ShieldCheck, Construction } from 'lucide-react';

const DIMENSIONS = [
  { key: 'empathy',        label: 'Empathy',        description: 'Did the agent acknowledge and validate customer feelings?' },
  { key: 'tone',           label: 'Tone',            description: 'Was the agent professional and courteous throughout?' },
  { key: 'resolution',     label: 'Resolution',      description: 'Was the customer\'s issue fully resolved?' },
  { key: 'professionalism',label: 'Professionalism', description: 'Did the agent follow correct procedures and language?' },
];

interface QAScorePanelProps {
  scores?: Record<string, number> | null;
}

export function QAScorePanel({ scores }: QAScorePanelProps) {
  const isStub = !scores;

  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900 overflow-hidden">
      <div className="flex items-center gap-2 px-4 py-3 border-b border-slate-800">
        <ShieldCheck size={15} className="text-indigo-400" />
        <h2 className="text-sm font-semibold text-slate-200">QA Score</h2>
        {isStub && (
          <span className="ml-auto inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-amber-500/20 text-amber-300 border border-amber-500/30">
            <Construction size={10} /> Coming soon
          </span>
        )}
      </div>

      <div className="p-4 space-y-4">
        {isStub && (
          <p className="text-xs text-slate-500 mb-3">
            Quality scores are generated by the QA Scoring Agent (function calling + rubric). Available once the agent is deployed.
          </p>
        )}

        {DIMENSIONS.map((dim) => {
          const score = scores?.[dim.key] ?? null;
          const pct = score !== null ? Math.round(score * 100) : null;

          let barColor = 'bg-slate-700';
          if (pct !== null) {
            barColor = pct >= 80 ? 'bg-emerald-500' : pct >= 50 ? 'bg-amber-500' : 'bg-rose-500';
          }

          return (
            <div key={dim.key} className="space-y-1.5">
              <div className="flex items-center justify-between text-xs">
                <span className="text-slate-300 font-medium">{dim.label}</span>
                <span className={`font-semibold tabular-nums ${pct === null ? 'text-slate-600' : pct >= 80 ? 'text-emerald-400' : pct >= 50 ? 'text-amber-400' : 'text-rose-400'}`}>
                  {pct !== null ? `${pct}%` : '—'}
                </span>
              </div>
              <div className="h-2 rounded-full bg-slate-800 overflow-hidden">
                <div
                  className={`h-full rounded-full transition-all duration-500 ${barColor}`}
                  style={{ width: pct !== null ? `${pct}%` : '0%' }}
                />
              </div>
              <p className="text-xs text-slate-600">{dim.description}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
